### ISSUE TITLE
Mistake in README - `biodatasets` vs `bio-datasets.` 

### ISSUE THREAD

**Issue by sgrimbly** [DeepChainBio/bio-datasets#14]
It seems like the installation instruction for `pip` is `pip install bio-datasets` but the import uses `import biodatasets.` Might want to fix this on the README.md for new users 😄.

**Comment by theomeb** [comment]
Thanks for noticing it 😃  This has been fixed with 10f67062a2ff379e6a109175396cbf327cb6702a.
